version: 2
builds:
  - main: ./cmd/dockguard
    binary: dockguard
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

dockers:
  - image_templates:
      - "narrowcastdev/dockguard:{{ .Version }}"
      - "narrowcastdev/dockguard:latest"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=dockguard"
      - "--label=org.opencontainers.image.version={{.Version}}"

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
