package hardener

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/narrowcastdev/dockguard/internal/compose"
	"github.com/narrowcastdev/dockguard/internal/rule"
	"gopkg.in/yaml.v3"
)

// HardenFile reads the input compose file, applies fixes, and writes the result.
// V1 re-serializes from the typed model (loses comments and original formatting).
// A future version can use yaml.Node manipulation for format preservation.
func HardenFile(inputPath, outputPath, version string, fixes []rule.Fix) error {
	abs1, _ := filepath.Abs(inputPath)
	abs2, _ := filepath.Abs(outputPath)
	if abs1 != "" && abs2 != "" && abs1 == abs2 {
		return fmt.Errorf("output path cannot be the same as input path")
	}

	data, err := os.ReadFile(inputPath)
	if err != nil {
		return fmt.Errorf("reading input: %w", err)
	}

	// Parse into typed model for fix application.
	f, err := compose.Parse(data)
	if err != nil {
		return fmt.Errorf("parsing input: %w", err)
	}

	// Apply all fixes to the typed model.
	for _, fix := range fixes {
		svc, ok := f.Services[fix.Service]
		if !ok {
			continue
		}
		fix.Apply(svc)
	}

	// Sync Environment back to RawEnv for serialization.
	f.PrepareForMarshal()

	// Re-serialize the fixed model.
	out, err := yaml.Marshal(f)
	if err != nil {
		return fmt.Errorf("marshaling hardened file: %w", err)
	}

	header := fmt.Sprintf("# Generated by dockguard %s — review changes before applying\n\n", version)
	result := []byte(header + string(out))

	if err := os.MkdirAll(filepath.Dir(outputPath), 0o755); err != nil {
		return fmt.Errorf("creating output directory: %w", err)
	}

	if err := os.WriteFile(outputPath, result, 0o644); err != nil {
		return fmt.Errorf("writing output: %w", err)
	}

	return nil
}
