package hardener_test

import (
	"os"
	"strings"
	"testing"

	"github.com/narrowcastdev/dockguard/internal/compose"
	"github.com/narrowcastdev/dockguard/internal/hardener"
	"github.com/narrowcastdev/dockguard/internal/rule"

	// Register all rules.
	_ "github.com/narrowcastdev/dockguard/internal/rule"
)

func TestHardenBasicFile(t *testing.T) {
	inputPath := "../../testdata/basic.yml"
	outputPath := t.TempDir() + "/hardened.yml"

	f, err := compose.ParseFile(inputPath)
	if err != nil {
		t.Fatalf("parse error: %v", err)
	}

	fixes := rule.Fixes(f)
	if len(fixes) == 0 {
		t.Fatal("expected fixes for basic.yml")
	}

	err = hardener.HardenFile(inputPath, outputPath, "v0.1.0-test", fixes)
	if err != nil {
		t.Fatalf("harden error: %v", err)
	}

	data, err := os.ReadFile(outputPath)
	if err != nil {
		t.Fatalf("read error: %v", err)
	}

	output := string(data)
	if !strings.Contains(output, "Generated by dockguard") {
		t.Error("expected dockguard header comment")
	}
	if !strings.Contains(output, "cap_drop") {
		t.Error("expected cap_drop in hardened output")
	}

	// Verify the hardened file is valid YAML by parsing it.
	_, err = compose.Parse(data)
	if err != nil {
		t.Fatalf("hardened file is not valid compose: %v", err)
	}
}
